# Generated by Django 5.0.2 on 2025-11-08 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_customwidget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customwidget',
            name='block_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='customwidget',
            unique_together={('user', 'block_id')},
        ),
    ]
